import { AlienDefinition, AlienType } from './types.js';

export const ALIEN_DEFINITIONS: Record<AlienType, AlienDefinition> = {
  heatblast: {
    type: 'heatblast',
    name: 'Heatblast',
    role: 'Ranged DPS',
    maxHp: 90,
    speed: 5.5,
    primaryDamage: 18,
    primaryCooldown: 0.5,
    primaryRange: 15,
    specialDamage: 30,
    specialCooldown: 6,
    specialRange: 5,
    specialDuration: 0.5,
    bodyRadius: 0.6,
    color: 0xff4400,
    glowColor: 0xff8800,
    description: 'Fireball projectiles and a devastating fire ring AoE',
  },
  fourarms: {
    type: 'fourarms',
    name: 'Four Arms',
    role: 'Melee Brawler',
    maxHp: 140,
    speed: 4.5,
    primaryDamage: 28,
    primaryCooldown: 0.7,
    primaryRange: 2.5,
    specialDamage: 35,
    specialCooldown: 8,
    specialRange: 4,
    specialDuration: 0.6,
    bodyRadius: 0.8,
    color: 0xcc0000,
    glowColor: 0xff2222,
    description: 'Devastating melee punches and a ground slam that stuns',
  },
  xlr8: {
    type: 'xlr8',
    name: 'XLR8',
    role: 'Assassin',
    maxHp: 75,
    speed: 8,
    primaryDamage: 15,
    primaryCooldown: 0.35,
    primaryRange: 2,
    specialDamage: 10,
    specialCooldown: 5,
    specialRange: 8,
    specialDuration: 0.3,
    bodyRadius: 0.5,
    color: 0x0088ff,
    glowColor: 0x44bbff,
    description: 'Lightning-fast slashes and an invulnerable speed dash',
  },
  diamondhead: {
    type: 'diamondhead',
    name: 'Diamondhead',
    role: 'Tank',
    maxHp: 130,
    speed: 4.0,
    primaryDamage: 14,
    primaryCooldown: 0.6,
    primaryRange: 12,
    specialDamage: 0,
    specialCooldown: 7,
    specialRange: 0,
    specialDuration: 2.0,
    bodyRadius: 0.7,
    color: 0x00cc66,
    glowColor: 0x44ff99,
    description: 'Crystal shard projectiles and an impenetrable crystal shield',
  },
};

export const ALIEN_TYPES: AlienType[] = ['heatblast', 'fourarms', 'xlr8', 'diamondhead'];
